var schoolsdata = [
  {
    "COUNTY":"BARINGO",
    "CONSTITUENCY":"BARINGO CENTRAL",
    "YES":114,
    "NOT":26,
    "TOTAL":140
  },
  {
    "COUNTY":"BARINGO",
    "CONSTITUENCY":"BARINGO  NORTH",
    "YES":130,
    "NOT":29,
    "TOTAL":159
  },
  {
    "COUNTY":"BARINGO",
    "CONSTITUENCY":"BARINGO SOUTH",
    "YES":70,
    "NOT":19,
    "TOTAL":89
  },
  {
    "COUNTY":"BARINGO",
    "CONSTITUENCY":"ELDAMA RAVINE",
    "YES":88,
    "NOT":12,
    "TOTAL":100
  },
  {
    "COUNTY":"BARINGO",
    "CONSTITUENCY":"MOGOTIO",
    "YES":85,
    "NOT":22,
    "TOTAL":107
  },
  {
    "COUNTY":"BARINGO",
    "CONSTITUENCY":"TIATY",
    "YES":67,
    "NOT":35,
    "TOTAL":102
  },
  {
    "COUNTY":"BARINGO",
    "CONSTITUENCY":"TOTAL",
    "YES":554,
    "NOT":143,
    "TOTAL":697
  },
  {
    "COUNTY":"BOMET",
    "CONSTITUENCY":"BOMET CENTRAL",
    "YES":83,
    "NOT":32,
    "TOTAL":115
  },
  {
    "COUNTY":"BOMET",
    "CONSTITUENCY":"BOMET EAST",
    "YES":64,
    "NOT":41,
    "TOTAL":105
  },
  {
    "COUNTY":"BOMET",
    "CONSTITUENCY":"CHEPALUNGU",
    "YES":115,
    "NOT":51,
    "TOTAL":166
  },
  {
    "COUNTY":"BOMET",
    "CONSTITUENCY":"KONOIN",
    "YES":107,
    "NOT":4,
    "TOTAL":111
  },
  {
    "COUNTY":"BOMET",
    "CONSTITUENCY":"SOTIK",
    "YES":148,
    "NOT":22,
    "TOTAL":170
  },
  {
    "COUNTY":"BOMET",
    "CONSTITUENCY":"TOTAL",
    "YES":517,
    "NOT":150,
    "TOTAL":667
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"BUMULA",
    "YES":84,
    "NOT":8,
    "TOTAL":92
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"KABUCHAI",
    "YES":78,
    "NOT":10,
    "TOTAL":88
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"KANDUYI",
    "YES":87,
    "NOT":5,
    "TOTAL":92
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"KIMILILI",
    "YES":61,
    "NOT":12,
    "TOTAL":73
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"MT ELGON",
    "YES":92,
    "NOT":20,
    "TOTAL":112
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"SIRISIA",
    "YES":78,
    "NOT":9,
    "TOTAL":87
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"TONGAREN",
    "YES":65,
    "NOT":1,
    "TOTAL":66
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"WEBUYE EAST",
    "YES":52,
    "NOT":15,
    "TOTAL":67
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"WEBUYE WEST",
    "YES":56,
    "NOT":13,
    "TOTAL":69
  },
  {
    "COUNTY":"BUNGOMA",
    "CONSTITUENCY":"TOTAL",
    "YES":653,
    "NOT":93,
    "TOTAL":746
  },
  {
    "COUNTY":"BUSIA",
    "CONSTITUENCY":"BUDALANGI",
    "YES":31,
    "NOT":7,
    "TOTAL":38
  },
  {
    "COUNTY":"BUSIA",
    "CONSTITUENCY":"BUTULA",
    "YES":54,
    "NOT":5,
    "TOTAL":59
  },
  {
    "COUNTY":"BUSIA",
    "CONSTITUENCY":"FUNYULA",
    "YES":55,
    "NOT":8,
    "TOTAL":63
  },
  {
    "COUNTY":"BUSIA",
    "CONSTITUENCY":"MATAYOS",
    "YES":31,
    "NOT":13,
    "TOTAL":44
  },
  {
    "COUNTY":"BUSIA",
    "CONSTITUENCY":"NAMBALE",
    "YES":48,
    "NOT":3,
    "TOTAL":51
  },
  {
    "COUNTY":"BUSIA",
    "CONSTITUENCY":"TESO NORTH",
    "YES":47,
    "NOT":42,
    "TOTAL":89
  },
  {
    "COUNTY":"BUSIA",
    "CONSTITUENCY":"TESO SOUTH",
    "YES":49,
    "NOT":29,
    "TOTAL":78
  },
  {
    "COUNTY":"BUSIA",
    "CONSTITUENCY":"TOTAL",
    "YES":315,
    "NOT":107,
    "TOTAL":422
  },
  {
    "COUNTY":"ELGEYO/MARAKWET",
    "CONSTITUENCY":"KEIYO NORTH",
    "YES":58,
    "NOT":10,
    "TOTAL":68
  },
  {
    "COUNTY":"ELGEYO/MARAKWET",
    "CONSTITUENCY":"KEIYO SOUTH",
    "YES":116,
    "NOT":9,
    "TOTAL":125
  },
  {
    "COUNTY":"ELGEYO/MARAKWET",
    "CONSTITUENCY":"MARAKWET EAST",
    "YES":57,
    "NOT":42,
    "TOTAL":99
  },
  {
    "COUNTY":"ELGEYO/MARAKWET",
    "CONSTITUENCY":"MARAKWET WEST",
    "YES":72,
    "NOT":21,
    "TOTAL":93
  },
  {
    "COUNTY":"ELGEYO/MARAKWET",
    "CONSTITUENCY":"TOTAL",
    "YES":303,
    "NOT":82,
    "TOTAL":385
  },
  {
    "COUNTY":"EMBU",
    "CONSTITUENCY":"MANYATTA",
    "YES":44,
    "NOT":9,
    "TOTAL":53
  },
  {
    "COUNTY":"EMBU",
    "CONSTITUENCY":"MBEERE NORTH",
    "YES":70,
    "NOT":33,
    "TOTAL":103
  },
  {
    "COUNTY":"EMBU",
    "CONSTITUENCY":"MBEERE SOUTH",
    "YES":88,
    "NOT":27,
    "TOTAL":115
  },
  {
    "COUNTY":"EMBU",
    "CONSTITUENCY":"RUNYENJES",
    "YES":81,
    "NOT":3,
    "TOTAL":84
  },
  {
    "COUNTY":"EMBU",
    "CONSTITUENCY":"TOTAL",
    "YES":283,
    "NOT":72,
    "TOTAL":355
  },
  {
    "COUNTY":"GARISSA",
    "CONSTITUENCY":"BALAMBALA",
    "YES":17,
    "NOT":2,
    "TOTAL":19
  },
  {
    "COUNTY":"GARISSA",
    "CONSTITUENCY":"DADAAB",
    "YES":22,
    "NOT":7,
    "TOTAL":29
  },
  {
    "COUNTY":"GARISSA",
    "CONSTITUENCY":"FAFI",
    "YES":28,
    "NOT":5,
    "TOTAL":33
  },
  {
    "COUNTY":"GARISSA",
    "CONSTITUENCY":"GARISSA",
    "YES":39,
    "NOT":0,
    "TOTAL":39
  },
  {
    "COUNTY":"GARISSA",
    "CONSTITUENCY":"IJARA",
    "YES":32,
    "NOT":17,
    "TOTAL":49
  },
  {
    "COUNTY":"GARISSA",
    "CONSTITUENCY":"LAGDERA",
    "YES":26,
    "NOT":16,
    "TOTAL":42
  },
  {
    "COUNTY":"GARISSA",
    "CONSTITUENCY":"TOTAL",
    "YES":164,
    "NOT":47,
    "TOTAL":211
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"HOMABAY  TOWN",
    "YES":40,
    "NOT":24,
    "TOTAL":64
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"KABONDO  KASIPUL",
    "YES":72,
    "NOT":33,
    "TOTAL":105
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"KARACHUONYO",
    "YES":120,
    "NOT":58,
    "TOTAL":178
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"KASIPUL",
    "YES":59,
    "NOT":19,
    "TOTAL":78
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"MBITA",
    "YES":47,
    "NOT":29,
    "TOTAL":76
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"NDHIWA",
    "YES":75,
    "NOT":77,
    "TOTAL":152
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"RANGWE",
    "YES":77,
    "NOT":30,
    "TOTAL":107
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"SUBA",
    "YES":57,
    "NOT":40,
    "TOTAL":97
  },
  {
    "COUNTY":"HOMA BAY",
    "CONSTITUENCY":"TOTAL",
    "YES":547,
    "NOT":310,
    "TOTAL":857
  },
  {
    "COUNTY":"ISIOLO",
    "CONSTITUENCY":"ISIOLO NORTH",
    "YES":72,
    "NOT":0,
    "TOTAL":72
  },
  {
    "COUNTY":"ISIOLO",
    "CONSTITUENCY":"ISIOLO SOUTH",
    "YES":39,
    "NOT":0,
    "TOTAL":39
  },
  {
    "COUNTY":"ISIOLO",
    "CONSTITUENCY":"TOTAL",
    "YES":111,
    "NOT":0,
    "TOTAL":111
  },
  {
    "COUNTY":"KAJIADO",
    "CONSTITUENCY":"KAJIADO  CENTRAL",
    "YES":95,
    "NOT":30,
    "TOTAL":125
  },
  {
    "COUNTY":"KAJIADO",
    "CONSTITUENCY":"KAJIADO EAST",
    "YES":60,
    "NOT":40,
    "TOTAL":100
  },
  {
    "COUNTY":"KAJIADO",
    "CONSTITUENCY":"KAJIADO NORTH",
    "YES":53,
    "NOT":26,
    "TOTAL":79
  },
  {
    "COUNTY":"KAJIADO",
    "CONSTITUENCY":"KAJIADO SOUTH",
    "YES":66,
    "NOT":22,
    "TOTAL":88
  },
  {
    "COUNTY":"KAJIADO",
    "CONSTITUENCY":"KAJIADO WEST",
    "YES":33,
    "NOT":22,
    "TOTAL":55
  },
  {
    "COUNTY":"KAJIADO",
    "CONSTITUENCY":"TOTAL",
    "YES":307,
    "NOT":140,
    "TOTAL":447
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"BUTERE",
    "YES":73,
    "NOT":5,
    "TOTAL":78
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"KHWISERO",
    "YES":60,
    "NOT":8,
    "TOTAL":68
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"LUGARI",
    "YES":87,
    "NOT":4,
    "TOTAL":91
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"LURAMBI",
    "YES":87,
    "NOT":8,
    "TOTAL":95
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"LIKUYANI",
    "YES":69,
    "NOT":3,
    "TOTAL":72
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"MALAVA",
    "YES":113,
    "NOT":1,
    "TOTAL":114
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"MATUNGU",
    "YES":46,
    "NOT":13,
    "TOTAL":59
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"IKOLOMANI",
    "YES":78,
    "NOT":0,
    "TOTAL":78
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"MUMIAS EAST",
    "YES":41,
    "NOT":5,
    "TOTAL":46
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"MUMIAS WEST",
    "YES":43,
    "NOT":0,
    "TOTAL":43
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"NAVAKHOLO",
    "YES":43,
    "NOT":1,
    "TOTAL":44
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"SHINYALU",
    "YES":30,
    "NOT":5,
    "TOTAL":35
  },
  {
    "COUNTY":"KAKAMEGA",
    "CONSTITUENCY":"TOTAL",
    "YES":770,
    "NOT":53,
    "TOTAL":823
  },
  {
    "COUNTY":"KERICHO",
    "CONSTITUENCY":"AINAMOI",
    "YES":67,
    "NOT":2,
    "TOTAL":69
  },
  {
    "COUNTY":"KERICHO",
    "CONSTITUENCY":"BELGUT",
    "YES":62,
    "NOT":2,
    "TOTAL":64
  },
  {
    "COUNTY":"KERICHO",
    "CONSTITUENCY":"BURET",
    "YES":100,
    "NOT":3,
    "TOTAL":103
  },
  {
    "COUNTY":"KERICHO",
    "CONSTITUENCY":"KIPKELION EAST",
    "YES":83,
    "NOT":2,
    "TOTAL":85
  },
  {
    "COUNTY":"KERICHO",
    "CONSTITUENCY":"KIPKELION  WEST",
    "YES":80,
    "NOT":6,
    "TOTAL":86
  },
  {
    "COUNTY":"KERICHO",
    "CONSTITUENCY":"SIGOWET/SOIN",
    "YES":81,
    "NOT":8,
    "TOTAL":89
  },
  {
    "COUNTY":"KERICHO",
    "CONSTITUENCY":"TOTAL",
    "YES":473,
    "NOT":23,
    "TOTAL":496
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"GATUNDU  NORTH",
    "YES":57,
    "NOT":4,
    "TOTAL":61
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"GATUNDU  SOUTH",
    "YES":52,
    "NOT":2,
    "TOTAL":54
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"GITHUNGURI",
    "YES":65,
    "NOT":1,
    "TOTAL":66
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"JUJA",
    "YES":44,
    "NOT":1,
    "TOTAL":45
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"KABETE",
    "YES":15,
    "NOT":0,
    "TOTAL":15
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"KIAMBAA",
    "YES":35,
    "NOT":5,
    "TOTAL":40
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"KIAMBU TOWN",
    "YES":4,
    "NOT":0,
    "TOTAL":4
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"KIKUYU",
    "YES":46,
    "NOT":2,
    "TOTAL":48
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"LARI",
    "YES":71,
    "NOT":1,
    "TOTAL":72
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"LIMURU",
    "YES":41,
    "NOT":1,
    "TOTAL":42
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"RUIRU",
    "YES":22,
    "NOT":3,
    "TOTAL":25
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"THIKA TOWN",
    "YES":23,
    "NOT":6,
    "TOTAL":29
  },
  {
    "COUNTY":"KIAMBU",
    "CONSTITUENCY":"TOTAL",
    "YES":475,
    "NOT":26,
    "TOTAL":501
  },
  {
    "COUNTY":"KILIFI",
    "CONSTITUENCY":"GANZE",
    "YES":69,
    "NOT":28,
    "TOTAL":97
  },
  {
    "COUNTY":"KILIFI",
    "CONSTITUENCY":"KALOLENI",
    "YES":50,
    "NOT":11,
    "TOTAL":61
  },
  {
    "COUNTY":"KILIFI",
    "CONSTITUENCY":"KILIFI NORTH",
    "YES":41,
    "NOT":9,
    "TOTAL":50
  },
  {
    "COUNTY":"KILIFI",
    "CONSTITUENCY":"KILIFI SOUTH",
    "YES":57,
    "NOT":9,
    "TOTAL":66
  },
  {
    "COUNTY":"KILIFI",
    "CONSTITUENCY":"MAGARINI",
    "YES":52,
    "NOT":31,
    "TOTAL":83
  },
  {
    "COUNTY":"KILIFI",
    "CONSTITUENCY":"MALINDI",
    "YES":56,
    "NOT":14,
    "TOTAL":70
  },
  {
    "COUNTY":"KILIFI",
    "CONSTITUENCY":"RABAI",
    "YES":35,
    "NOT":6,
    "TOTAL":41
  },
  {
    "COUNTY":"KILIFI",
    "CONSTITUENCY":"TOTAL",
    "YES":360,
    "NOT":108,
    "TOTAL":468
  },
  {
    "COUNTY":"KIRINYAGA",
    "CONSTITUENCY":"GICHUGU",
    "YES":38,
    "NOT":1,
    "TOTAL":39
  },
  {
    "COUNTY":"KIRINYAGA",
    "CONSTITUENCY":"KIRINYAGA  CENTRAL",
    "YES":38,
    "NOT":1,
    "TOTAL":39
  },
  {
    "COUNTY":"KIRINYAGA",
    "CONSTITUENCY":"MWEA",
    "YES":68,
    "NOT":6,
    "TOTAL":74
  },
  {
    "COUNTY":"KIRINYAGA",
    "CONSTITUENCY":"NDIA",
    "YES":40,
    "NOT":1,
    "TOTAL":41
  },
  {
    "COUNTY":"KIRINYAGA",
    "CONSTITUENCY":"TOTAL",
    "YES":184,
    "NOT":9,
    "TOTAL":193
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"BOBASI",
    "YES":110,
    "NOT":12,
    "TOTAL":122
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"BOMACHOGE BORABU",
    "YES":120,
    "NOT":0,
    "TOTAL":120
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"BOMACHOGE  CHACHE",
    "YES":31,
    "NOT":0,
    "TOTAL":31
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"BONCHARI",
    "YES":54,
    "NOT":4,
    "TOTAL":58
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"KITUTU CHACHE NORTH",
    "YES":97,
    "NOT":5,
    "TOTAL":102
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"KITUTU CHACHE SOUTH",
    "YES":55,
    "NOT":2,
    "TOTAL":57
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"NYARIBARI CHACHE",
    "YES":73,
    "NOT":0,
    "TOTAL":73
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"NYARIBARI  MASABA",
    "YES":72,
    "NOT":1,
    "TOTAL":73
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"SOUTH MUGIRANGO",
    "YES":85,
    "NOT":5,
    "TOTAL":90
  },
  {
    "COUNTY":"KISII",
    "CONSTITUENCY":"TOTAL",
    "YES":697,
    "NOT":29,
    "TOTAL":726
  },
  {
    "COUNTY":"KISUMU",
    "CONSTITUENCY":"KISUMU EAST",
    "YES":37,
    "NOT":0,
    "TOTAL":37
  },
  {
    "COUNTY":"KISUMU",
    "CONSTITUENCY":"KISUMU WEST",
    "YES":85,
    "NOT":7,
    "TOTAL":92
  },
  {
    "COUNTY":"KISUMU",
    "CONSTITUENCY":"MUHORONI",
    "YES":83,
    "NOT":21,
    "TOTAL":104
  },
  {
    "COUNTY":"KISUMU",
    "CONSTITUENCY":"NYAKACH",
    "YES":118,
    "NOT":24,
    "TOTAL":142
  },
  {
    "COUNTY":"KISUMU",
    "CONSTITUENCY":"NYANDO",
    "YES":85,
    "NOT":10,
    "TOTAL":95
  },
  {
    "COUNTY":"KISUMU",
    "CONSTITUENCY":"SEME",
    "YES":93,
    "NOT":19,
    "TOTAL":112
  },
  {
    "COUNTY":"KISUMU",
    "CONSTITUENCY":"TOTAL",
    "YES":501,
    "NOT":81,
    "TOTAL":582
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"KITUI CENTRAL",
    "YES":120,
    "NOT":39,
    "TOTAL":159
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"KITUI EAST",
    "YES":145,
    "NOT":32,
    "TOTAL":177
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"KITUI RURAL",
    "YES":43,
    "NOT":6,
    "TOTAL":49
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"KITUI SOUTH",
    "YES":186,
    "NOT":101,
    "TOTAL":287
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"KITUI WEST",
    "YES":81,
    "NOT":6,
    "TOTAL":87
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"MWINGI CENTRAL",
    "YES":53,
    "NOT":47,
    "TOTAL":100
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"MWINGI NORTH",
    "YES":138,
    "NOT":89,
    "TOTAL":227
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"MWINGI WEST",
    "YES":66,
    "NOT":19,
    "TOTAL":85
  },
  {
    "COUNTY":"KITUI",
    "CONSTITUENCY":"TOTAL",
    "YES":832,
    "NOT":339,
    "TOTAL":1171
  },
  {
    "COUNTY":"KWALE",
    "CONSTITUENCY":"KINANGO",
    "YES":80,
    "NOT":54,
    "TOTAL":134
  },
  {
    "COUNTY":"KWALE",
    "CONSTITUENCY":"LUNGA LUNGA",
    "YES":8,
    "NOT":12,
    "TOTAL":20
  },
  {
    "COUNTY":"KWALE",
    "CONSTITUENCY":"MATUGA",
    "YES":72,
    "NOT":26,
    "TOTAL":98
  },
  {
    "COUNTY":"KWALE",
    "CONSTITUENCY":"MSAMBWENI",
    "YES":84,
    "NOT":27,
    "TOTAL":111
  },
  {
    "COUNTY":"KWALE",
    "CONSTITUENCY":"TOTAL",
    "YES":244,
    "NOT":119,
    "TOTAL":363
  },
  {
    "COUNTY":"LAIKIPIA",
    "CONSTITUENCY":"LAIKIPIA EAST",
    "YES":57,
    "NOT":10,
    "TOTAL":67
  },
  {
    "COUNTY":"LAIKIPIA",
    "CONSTITUENCY":"LAIKIPIA NORTH",
    "YES":17,
    "NOT":10,
    "TOTAL":27
  },
  {
    "COUNTY":"LAIKIPIA",
    "CONSTITUENCY":"LAIKIPIA WEST",
    "YES":107,
    "NOT":18,
    "TOTAL":125
  },
  {
    "COUNTY":"LAIKIPIA",
    "CONSTITUENCY":"TOTAL",
    "YES":181,
    "NOT":38,
    "TOTAL":219
  },
  {
    "COUNTY":"LAMU",
    "CONSTITUENCY":"LAMU EAST",
    "YES":17,
    "NOT":1,
    "TOTAL":18
  },
  {
    "COUNTY":"LAMU",
    "CONSTITUENCY":"LAMU WEST",
    "YES":73,
    "NOT":0,
    "TOTAL":73
  },
  {
    "COUNTY":"LAMU",
    "CONSTITUENCY":"TOTAL",
    "YES":90,
    "NOT":1,
    "TOTAL":91
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"MACHAKOS  TOWN",
    "YES":101,
    "NOT":10,
    "TOTAL":111
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"MASINGA",
    "YES":97,
    "NOT":32,
    "TOTAL":129
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"MAVOKO",
    "YES":29,
    "NOT":6,
    "TOTAL":35
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"KANGUNDO",
    "YES":62,
    "NOT":4,
    "TOTAL":66
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"KATHIANI",
    "YES":67,
    "NOT":4,
    "TOTAL":71
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"MATUNGULU",
    "YES":75,
    "NOT":4,
    "TOTAL":79
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"MWALA",
    "YES":142,
    "NOT":30,
    "TOTAL":172
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"YATTA",
    "YES":78,
    "NOT":40,
    "TOTAL":118
  },
  {
    "COUNTY":"MACHAKOS",
    "CONSTITUENCY":"TOTAL",
    "YES":651,
    "NOT":130,
    "TOTAL":781
  },
  {
    "COUNTY":"MAKUENI",
    "CONSTITUENCY":"KAITI",
    "YES":71,
    "NOT":30,
    "TOTAL":101
  },
  {
    "COUNTY":"MAKUENI",
    "CONSTITUENCY":"KIBWEZI EAST",
    "YES":54,
    "NOT":39,
    "TOTAL":93
  },
  {
    "COUNTY":"MAKUENI",
    "CONSTITUENCY":"KIBWEZI WEST",
    "YES":84,
    "NOT":51,
    "TOTAL":135
  },
  {
    "COUNTY":"MAKUENI",
    "CONSTITUENCY":"KILOME",
    "YES":82,
    "NOT":17,
    "TOTAL":99
  },
  {
    "COUNTY":"MAKUENI",
    "CONSTITUENCY":"MAKUENI",
    "YES":137,
    "NOT":55,
    "TOTAL":192
  },
  {
    "COUNTY":"MAKUENI",
    "CONSTITUENCY":"MBOONI",
    "YES":112,
    "NOT":51,
    "TOTAL":163
  },
  {
    "COUNTY":"MAKUENI",
    "CONSTITUENCY":"TOTAL",
    "YES":540,
    "NOT":243,
    "TOTAL":783
  },
  {
    "COUNTY":"MANDERA",
    "CONSTITUENCY":"BANISA",
    "YES":22,
    "NOT":0,
    "TOTAL":22
  },
  {
    "COUNTY":"MANDERA",
    "CONSTITUENCY":"LAFEY",
    "YES":13,
    "NOT":0,
    "TOTAL":13
  },
  {
    "COUNTY":"MANDERA",
    "CONSTITUENCY":"MANDERA EAST",
    "YES":57,
    "NOT":19,
    "TOTAL":76
  },
  {
    "COUNTY":"MANDERA",
    "CONSTITUENCY":"MANDERA NORTH",
    "YES":25,
    "NOT":0,
    "TOTAL":25
  },
  {
    "COUNTY":"MANDERA",
    "CONSTITUENCY":"MANDERA  SOUTH",
    "YES":37,
    "NOT":0,
    "TOTAL":37
  },
  {
    "COUNTY":"MANDERA",
    "CONSTITUENCY":"MANDERA WEST",
    "YES":46,
    "NOT":0,
    "TOTAL":46
  },
  {
    "COUNTY":"MANDERA",
    "CONSTITUENCY":"TOTAL",
    "YES":200,
    "NOT":19,
    "TOTAL":219
  },
  {
    "COUNTY":"MARSABIT",
    "CONSTITUENCY":"LAISAMIS",
    "YES":39,
    "NOT":3,
    "TOTAL":42
  },
  {
    "COUNTY":"MARSABIT",
    "CONSTITUENCY":"MOYALE",
    "YES":41,
    "NOT":14,
    "TOTAL":55
  },
  {
    "COUNTY":"MARSABIT",
    "CONSTITUENCY":"NORTH HORR",
    "YES":24,
    "NOT":8,
    "TOTAL":32
  },
  {
    "COUNTY":"MARSABIT",
    "CONSTITUENCY":"SAKU",
    "YES":25,
    "NOT":8,
    "TOTAL":33
  },
  {
    "COUNTY":"MARSABIT",
    "CONSTITUENCY":"TOTAL",
    "YES":129,
    "NOT":33,
    "TOTAL":162
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"BUURI",
    "YES":66,
    "NOT":13,
    "TOTAL":79
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"CENTRAL  IMENTI",
    "YES":73,
    "NOT":10,
    "TOTAL":83
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"IGEMBE  CENTRAL",
    "YES":35,
    "NOT":10,
    "TOTAL":45
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"IGEMBE NORTH",
    "YES":36,
    "NOT":12,
    "TOTAL":48
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"IGEMBE SOUTH",
    "YES":45,
    "NOT":20,
    "TOTAL":65
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"IMENTI NORTH",
    "YES":52,
    "NOT":4,
    "TOTAL":56
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"IMENTI SOUTH",
    "YES":96,
    "NOT":4,
    "TOTAL":100
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"TIGANIA EAST",
    "YES":50,
    "NOT":8,
    "TOTAL":58
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"TIGANIA WEST",
    "YES":58,
    "NOT":18,
    "TOTAL":76
  },
  {
    "COUNTY":"MERU",
    "CONSTITUENCY":"TOTAL",
    "YES":511,
    "NOT":99,
    "TOTAL":610
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"AWENDO",
    "YES":33,
    "NOT":10,
    "TOTAL":43
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"KURIA EAST",
    "YES":47,
    "NOT":12,
    "TOTAL":59
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"KURIA WEST",
    "YES":72,
    "NOT":23,
    "TOTAL":95
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"NYATIKE",
    "YES":82,
    "NOT":43,
    "TOTAL":125
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"RONGO",
    "YES":74,
    "NOT":26,
    "TOTAL":100
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"SUNA EAST",
    "YES":67,
    "NOT":21,
    "TOTAL":88
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"SUNA WEST",
    "YES":23,
    "NOT":15,
    "TOTAL":38
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"URIRI",
    "YES":55,
    "NOT":23,
    "TOTAL":78
  },
  {
    "COUNTY":"MIGORI",
    "CONSTITUENCY":"TOTAL",
    "YES":453,
    "NOT":173,
    "TOTAL":626
  },
  {
    "COUNTY":"MOMBASA",
    "CONSTITUENCY":"CHANGAMWE",
    "YES":11,
    "NOT":0,
    "TOTAL":11
  },
  {
    "COUNTY":"MOMBASA",
    "CONSTITUENCY":"JOMVU",
    "YES":7,
    "NOT":1,
    "TOTAL":8
  },
  {
    "COUNTY":"MOMBASA",
    "CONSTITUENCY":"KISAUNI",
    "YES":14,
    "NOT":1,
    "TOTAL":15
  },
  {
    "COUNTY":"MOMBASA",
    "CONSTITUENCY":"NYALI",
    "YES":11,
    "NOT":0,
    "TOTAL":11
  },
  {
    "COUNTY":"MOMBASA",
    "CONSTITUENCY":"LIKONI",
    "YES":19,
    "NOT":0,
    "TOTAL":19
  },
  {
    "COUNTY":"MOMBASA",
    "CONSTITUENCY":"MVITA",
    "YES":29,
    "NOT":0,
    "TOTAL":29
  },
  {
    "COUNTY":"MOMBASA",
    "CONSTITUENCY":"TOTAL",
    "YES":91,
    "NOT":2,
    "TOTAL":93
  },
  {
    "COUNTY":"MURANGA",
    "CONSTITUENCY":"GATANGA",
    "YES":71,
    "NOT":4,
    "TOTAL":75
  },
  {
    "COUNTY":"MURANGA",
    "CONSTITUENCY":"KANDARA",
    "YES":72,
    "NOT":3,
    "TOTAL":75
  },
  {
    "COUNTY":"MURANGA",
    "CONSTITUENCY":"KANGEMA",
    "YES":36,
    "NOT":0,
    "TOTAL":36
  },
  {
    "COUNTY":"MURANGA",
    "CONSTITUENCY":"KIGUMO",
    "YES":58,
    "NOT":3,
    "TOTAL":61
  },
  {
    "COUNTY":"MURANGA",
    "CONSTITUENCY":"KIHARU",
    "YES":103,
    "NOT":4,
    "TOTAL":107
  },
  {
    "COUNTY":"MURANGA",
    "CONSTITUENCY":"MARAGWA",
    "YES":58,
    "NOT":4,
    "TOTAL":62
  },
  {
    "COUNTY":"MURANGA",
    "CONSTITUENCY":"MATHIOYA",
    "YES":59,
    "NOT":1,
    "TOTAL":60
  },
  {
    "COUNTY":"MURANGA",
    "CONSTITUENCY":"TOTAL",
    "YES":457,
    "NOT":19,
    "TOTAL":476
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"DAGORETTI  NORTH",
    "YES":15,
    "NOT":0,
    "TOTAL":15
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"DAGORETTI  SOUTH",
    "YES":16,
    "NOT":0,
    "TOTAL":16
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"EMBAKASI  CENTRAL",
    "YES":7,
    "NOT":0,
    "TOTAL":7
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"EMBAKASI EAST",
    "YES":8,
    "NOT":0,
    "TOTAL":8
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"EMBAKASI  NORTH",
    "YES":8,
    "NOT":0,
    "TOTAL":8
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"EMBAKASI  SOUTH",
    "YES":6,
    "NOT":0,
    "TOTAL":6
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"EMBAKASI  WEST",
    "YES":7,
    "NOT":1,
    "TOTAL":8
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"KAMUKUNJI",
    "YES":18,
    "NOT":0,
    "TOTAL":18
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"KASARANI",
    "YES":14,
    "NOT":0,
    "TOTAL":14
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"KIBRA",
    "YES":8,
    "NOT":0,
    "TOTAL":8
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"LANGATA",
    "YES":8,
    "NOT":0,
    "TOTAL":8
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"MAKADARA",
    "YES":23,
    "NOT":0,
    "TOTAL":23
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"MATHARE",
    "YES":8,
    "NOT":0,
    "TOTAL":8
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"ROYSAMBU",
    "YES":10,
    "NOT":0,
    "TOTAL":10
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"RUARAKA",
    "YES":8,
    "NOT":0,
    "TOTAL":8
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"STAREHE",
    "YES":20,
    "NOT":0,
    "TOTAL":20
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"WESTLANDS",
    "YES":19,
    "NOT":0,
    "TOTAL":19
  },
  {
    "COUNTY":"NAIROBI CITY",
    "CONSTITUENCY":"TOTAL",
    "YES":203,
    "NOT":1,
    "TOTAL":204
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"BAHATI",
    "YES":37,
    "NOT":0,
    "TOTAL":37
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"GILGIL",
    "YES":27,
    "NOT":35,
    "TOTAL":62
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"KURESOI  NORTH",
    "YES":49,
    "NOT":16,
    "TOTAL":65
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"KURESOI SOUTH",
    "YES":66,
    "NOT":16,
    "TOTAL":82
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"MOLO",
    "YES":63,
    "NOT":10,
    "TOTAL":73
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"NAIVASHA",
    "YES":68,
    "NOT":8,
    "TOTAL":76
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"NAKURU TOWN EAST",
    "YES":36,
    "NOT":6,
    "TOTAL":42
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"NAKURU TOWN WEST",
    "YES":25,
    "NOT":5,
    "TOTAL":30
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"NJORO",
    "YES":65,
    "NOT":11,
    "TOTAL":76
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"RONGAI",
    "YES":82,
    "NOT":16,
    "TOTAL":98
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"SUBUKIA",
    "YES":35,
    "NOT":13,
    "TOTAL":48
  },
  {
    "COUNTY":"NAKURU",
    "CONSTITUENCY":"TOTAL",
    "YES":553,
    "NOT":136,
    "TOTAL":689
  },
  {
    "COUNTY":"NANDI",
    "CONSTITUENCY":"ALDAI",
    "YES":44,
    "NOT":25,
    "TOTAL":69
  },
  {
    "COUNTY":"NANDI",
    "CONSTITUENCY":"CHESUMEI",
    "YES":88,
    "NOT":13,
    "TOTAL":101
  },
  {
    "COUNTY":"NANDI",
    "CONSTITUENCY":"EMGWEN",
    "YES":59,
    "NOT":14,
    "TOTAL":73
  },
  {
    "COUNTY":"NANDI",
    "CONSTITUENCY":"MOSOP",
    "YES":113,
    "NOT":26,
    "TOTAL":139
  },
  {
    "COUNTY":"NANDI",
    "CONSTITUENCY":"NANDI HILLS",
    "YES":42,
    "NOT":11,
    "TOTAL":53
  },
  {
    "COUNTY":"NANDI",
    "CONSTITUENCY":"TINDERET",
    "YES":52,
    "NOT":34,
    "TOTAL":86
  },
  {
    "COUNTY":"NANDI",
    "CONSTITUENCY":"TOTAL",
    "YES":398,
    "NOT":123,
    "TOTAL":521
  },
  {
    "COUNTY":"NAROK",
    "CONSTITUENCY":"EMURIA DIKIRR",
    "YES":27,
    "NOT":26,
    "TOTAL":53
  },
  {
    "COUNTY":"NAROK",
    "CONSTITUENCY":"KILGORIS",
    "YES":89,
    "NOT":24,
    "TOTAL":113
  },
  {
    "COUNTY":"NAROK",
    "CONSTITUENCY":"NAROK EAST",
    "YES":58,
    "NOT":32,
    "TOTAL":90
  },
  {
    "COUNTY":"NAROK",
    "CONSTITUENCY":"NAROK NORTH",
    "YES":94,
    "NOT":35,
    "TOTAL":129
  },
  {
    "COUNTY":"NAROK",
    "CONSTITUENCY":"NAROK SOUTH",
    "YES":101,
    "NOT":27,
    "TOTAL":128
  },
  {
    "COUNTY":"NAROK",
    "CONSTITUENCY":"NAROK WEST",
    "YES":33,
    "NOT":26,
    "TOTAL":59
  },
  {
    "COUNTY":"NAROK",
    "CONSTITUENCY":"TOTAL",
    "YES":402,
    "NOT":170,
    "TOTAL":572
  },
  {
    "COUNTY":"NYAMIRA",
    "CONSTITUENCY":"BORABU",
    "YES":53,
    "NOT":2,
    "TOTAL":55
  },
  {
    "COUNTY":"NYAMIRA",
    "CONSTITUENCY":"KITUTU MASABA",
    "YES":121,
    "NOT":11,
    "TOTAL":132
  },
  {
    "COUNTY":"NYAMIRA",
    "CONSTITUENCY":"NORTH  MUGIRANGO",
    "YES":104,
    "NOT":14,
    "TOTAL":118
  },
  {
    "COUNTY":"NYAMIRA",
    "CONSTITUENCY":"WEST  MUGIRANGO",
    "YES":86,
    "NOT":5,
    "TOTAL":91
  },
  {
    "COUNTY":"NYAMIRA",
    "CONSTITUENCY":"TOTAL",
    "YES":364,
    "NOT":32,
    "TOTAL":396
  },
  {
    "COUNTY":"NYANDARUA",
    "CONSTITUENCY":"KINANGOP",
    "YES":72,
    "NOT":6,
    "TOTAL":78
  },
  {
    "COUNTY":"NYANDARUA",
    "CONSTITUENCY":"KIPIPIRI",
    "YES":51,
    "NOT":11,
    "TOTAL":62
  },
  {
    "COUNTY":"NYANDARUA",
    "CONSTITUENCY":"NDARAGWA",
    "YES":60,
    "NOT":10,
    "TOTAL":70
  },
  {
    "COUNTY":"NYANDARUA",
    "CONSTITUENCY":"OL JORO OROK",
    "YES":28,
    "NOT":5,
    "TOTAL":33
  },
  {
    "COUNTY":"NYANDARUA",
    "CONSTITUENCY":"OL KALOU",
    "YES":78,
    "NOT":4,
    "TOTAL":82
  },
  {
    "COUNTY":"NYANDARUA",
    "CONSTITUENCY":"TOTAL",
    "YES":289,
    "NOT":36,
    "TOTAL":325
  },
  {
    "COUNTY":"NYERI",
    "CONSTITUENCY":"KIENI",
    "YES":85,
    "NOT":2,
    "TOTAL":87
  },
  {
    "COUNTY":"NYERI",
    "CONSTITUENCY":"MATHIRA",
    "YES":70,
    "NOT":0,
    "TOTAL":70
  },
  {
    "COUNTY":"NYERI",
    "CONSTITUENCY":"MUKURWEINI",
    "YES":64,
    "NOT":0,
    "TOTAL":64
  },
  {
    "COUNTY":"NYERI",
    "CONSTITUENCY":"NYERI TOWN",
    "YES":44,
    "NOT":0,
    "TOTAL":44
  },
  {
    "COUNTY":"NYERI",
    "CONSTITUENCY":"OTHAYA",
    "YES":56,
    "NOT":1,
    "TOTAL":57
  },
  {
    "COUNTY":"NYERI",
    "CONSTITUENCY":"TETU",
    "YES":46,
    "NOT":0,
    "TOTAL":46
  },
  {
    "COUNTY":"NYERI",
    "CONSTITUENCY":"TOTAL",
    "YES":365,
    "NOT":3,
    "TOTAL":368
  },
  {
    "COUNTY":"SAMBURU",
    "CONSTITUENCY":"SAMBURU EAST",
    "YES":42,
    "NOT":1,
    "TOTAL":43
  },
  {
    "COUNTY":"SAMBURU",
    "CONSTITUENCY":"SAMBURU  NORTH",
    "YES":29,
    "NOT":2,
    "TOTAL":31
  },
  {
    "COUNTY":"SAMBURU",
    "CONSTITUENCY":"SAMBURU WEST",
    "YES":81,
    "NOT":21,
    "TOTAL":102
  },
  {
    "COUNTY":"SAMBURU",
    "CONSTITUENCY":"TOTAL",
    "YES":152,
    "NOT":24,
    "TOTAL":176
  },
  {
    "COUNTY":"SIAYA",
    "CONSTITUENCY":"ALEGO USONGA",
    "YES":87,
    "NOT":32,
    "TOTAL":119
  },
  {
    "COUNTY":"SIAYA",
    "CONSTITUENCY":"BONDO",
    "YES":90,
    "NOT":35,
    "TOTAL":125
  },
  {
    "COUNTY":"SIAYA",
    "CONSTITUENCY":"GEM",
    "YES":92,
    "NOT":22,
    "TOTAL":114
  },
  {
    "COUNTY":"SIAYA",
    "CONSTITUENCY":"RARIEDA",
    "YES":94,
    "NOT":34,
    "TOTAL":128
  },
  {
    "COUNTY":"SIAYA",
    "CONSTITUENCY":"UGENYA",
    "YES":68,
    "NOT":21,
    "TOTAL":89
  },
  {
    "COUNTY":"SIAYA",
    "CONSTITUENCY":"UGUNJA",
    "YES":66,
    "NOT":3,
    "TOTAL":69
  },
  {
    "COUNTY":"SIAYA",
    "CONSTITUENCY":"TOTAL",
    "YES":497,
    "NOT":147,
    "TOTAL":644
  },
  {
    "COUNTY":"TAITA TAVETA",
    "CONSTITUENCY":"MWATATE",
    "YES":50,
    "NOT":9,
    "TOTAL":59
  },
  {
    "COUNTY":"TAITA TAVETA",
    "CONSTITUENCY":"TAVETA",
    "YES":26,
    "NOT":2,
    "TOTAL":28
  },
  {
    "COUNTY":"TAITA TAVETA",
    "CONSTITUENCY":"VOI",
    "YES":51,
    "NOT":9,
    "TOTAL":60
  },
  {
    "COUNTY":"TAITA TAVETA",
    "CONSTITUENCY":"WUNDANYI",
    "YES":36,
    "NOT":5,
    "TOTAL":41
  },
  {
    "COUNTY":"TAITA TAVETA",
    "CONSTITUENCY":"TOTAL",
    "YES":163,
    "NOT":25,
    "TOTAL":188
  },
  {
    "COUNTY":"TANA RIVER",
    "CONSTITUENCY":"BURA",
    "YES":49,
    "NOT":0,
    "TOTAL":49
  },
  {
    "COUNTY":"TANA RIVER",
    "CONSTITUENCY":"GALOLE",
    "YES":58,
    "NOT":0,
    "TOTAL":58
  },
  {
    "COUNTY":"TANA RIVER",
    "CONSTITUENCY":"GARSEN",
    "YES":65,
    "NOT":0,
    "TOTAL":65
  },
  {
    "COUNTY":"TANA RIVER",
    "CONSTITUENCY":"TOTAL",
    "YES":172,
    "NOT":0,
    "TOTAL":172
  },
  {
    "COUNTY":"THARAKA NITHI",
    "CONSTITUENCY":"CHUKA/IGAMBA NGÓMBE",
    "YES":109,
    "NOT":40,
    "TOTAL":149
  },
  {
    "COUNTY":"THARAKA NITHI",
    "CONSTITUENCY":"MARAA",
    "YES":96,
    "NOT":5,
    "TOTAL":101
  },
  {
    "COUNTY":"THARAKA NITHI",
    "CONSTITUENCY":"THARAKA",
    "YES":141,
    "NOT":39,
    "TOTAL":180
  },
  {
    "COUNTY":"THARAKA NITHI",
    "CONSTITUENCY":"TOTAL",
    "YES":346,
    "NOT":84,
    "TOTAL":430
  },
  {
    "COUNTY":"TRANS NZOIA",
    "CONSTITUENCY":"CHERANGANY",
    "YES":66,
    "NOT":27,
    "TOTAL":93
  },
  {
    "COUNTY":"TRANS NZOIA",
    "CONSTITUENCY":"ENDEBESS",
    "YES":34,
    "NOT":11,
    "TOTAL":45
  },
  {
    "COUNTY":"TRANS NZOIA",
    "CONSTITUENCY":"KIMININI",
    "YES":55,
    "NOT":5,
    "TOTAL":60
  },
  {
    "COUNTY":"TRANS NZOIA",
    "CONSTITUENCY":"KWANZA",
    "YES":63,
    "NOT":12,
    "TOTAL":75
  },
  {
    "COUNTY":"TRANS NZOIA",
    "CONSTITUENCY":"SABOTI",
    "YES":60,
    "NOT":10,
    "TOTAL":70
  },
  {
    "COUNTY":"TRANS NZOIA",
    "CONSTITUENCY":"TOTAL",
    "YES":278,
    "NOT":65,
    "TOTAL":343
  },
  {
    "COUNTY":"TURKANA",
    "CONSTITUENCY":"LOIMA",
    "YES":30,
    "NOT":4,
    "TOTAL":34
  },
  {
    "COUNTY":"TURKANA",
    "CONSTITUENCY":"TURKANA CENTRAL",
    "YES":45,
    "NOT":36,
    "TOTAL":81
  },
  {
    "COUNTY":"TURKANA",
    "CONSTITUENCY":"TURKANA EAST",
    "YES":29,
    "NOT":11,
    "TOTAL":40
  },
  {
    "COUNTY":"TURKANA",
    "CONSTITUENCY":"TURKANA NORTH",
    "YES":64,
    "NOT":0,
    "TOTAL":64
  },
  {
    "COUNTY":"TURKANA",
    "CONSTITUENCY":"TURKANA SOUTH",
    "YES":51,
    "NOT":41,
    "TOTAL":92
  },
  {
    "COUNTY":"TURKANA",
    "CONSTITUENCY":"TURKANA WEST",
    "YES":65,
    "NOT":0,
    "TOTAL":65
  },
  {
    "COUNTY":"TURKANA",
    "CONSTITUENCY":"TOTAL",
    "YES":284,
    "NOT":92,
    "TOTAL":376
  },
  {
    "COUNTY":"UASIN GISHU",
    "CONSTITUENCY":"AINABKOI",
    "YES":38,
    "NOT":8,
    "TOTAL":46
  },
  {
    "COUNTY":"UASIN GISHU",
    "CONSTITUENCY":"KAPSERET",
    "YES":40,
    "NOT":0,
    "TOTAL":40
  },
  {
    "COUNTY":"UASIN GISHU",
    "CONSTITUENCY":"KESSES",
    "YES":36,
    "NOT":9,
    "TOTAL":45
  },
  {
    "COUNTY":"UASIN GISHU",
    "CONSTITUENCY":"MOIBEN",
    "YES":67,
    "NOT":25,
    "TOTAL":92
  },
  {
    "COUNTY":"UASIN GISHU",
    "CONSTITUENCY":"SOY",
    "YES":81,
    "NOT":19,
    "TOTAL":100
  },
  {
    "COUNTY":"UASIN GISHU",
    "CONSTITUENCY":"TURBO",
    "YES":69,
    "NOT":13,
    "TOTAL":82
  },
  {
    "COUNTY":"UASIN GISHU",
    "CONSTITUENCY":"TOTAL",
    "YES":331,
    "NOT":74,
    "TOTAL":405
  },
  {
    "COUNTY":"VIHIGA",
    "CONSTITUENCY":"EMUHAYA",
    "YES":56,
    "NOT":11,
    "TOTAL":67
  },
  {
    "COUNTY":"VIHIGA",
    "CONSTITUENCY":"HAMISI",
    "YES":94,
    "NOT":19,
    "TOTAL":113
  },
  {
    "COUNTY":"VIHIGA",
    "CONSTITUENCY":"LUANDA",
    "YES":25,
    "NOT":1,
    "TOTAL":26
  },
  {
    "COUNTY":"VIHIGA",
    "CONSTITUENCY":"SABATIA",
    "YES":96,
    "NOT":4,
    "TOTAL":100
  },
  {
    "COUNTY":"VIHIGA",
    "CONSTITUENCY":"VIHIGA",
    "YES":63,
    "NOT":6,
    "TOTAL":69
  },
  {
    "COUNTY":"VIHIGA",
    "CONSTITUENCY":"TOTAL",
    "YES":334,
    "NOT":41,
    "TOTAL":375
  },
  {
    "COUNTY":"WAJIR",
    "CONSTITUENCY":"ELDAS",
    "YES":18,
    "NOT":0,
    "TOTAL":18
  },
  {
    "COUNTY":"WAJIR",
    "CONSTITUENCY":"TARBAJ",
    "YES":16,
    "NOT":13,
    "TOTAL":29
  },
  {
    "COUNTY":"WAJIR",
    "CONSTITUENCY":"WAJIR EAST",
    "YES":46,
    "NOT":0,
    "TOTAL":46
  },
  {
    "COUNTY":"WAJIR",
    "CONSTITUENCY":"WAJIR NORTH",
    "YES":44,
    "NOT":0,
    "TOTAL":44
  },
  {
    "COUNTY":"WAJIR",
    "CONSTITUENCY":"WAJIR SOUTH",
    "YES":68,
    "NOT":6,
    "TOTAL":74
  },
  {
    "COUNTY":"WAJIR",
    "CONSTITUENCY":"WAJIR WEST",
    "YES":45,
    "NOT":0,
    "TOTAL":45
  },
  {
    "COUNTY":"WAJIR",
    "CONSTITUENCY":"TOTAL",
    "YES":237,
    "NOT":19,
    "TOTAL":256
  },
  {
    "COUNTY":"WEST POKOT",
    "CONSTITUENCY":"KACHELIBA",
    "YES":74,
    "NOT":36,
    "TOTAL":110
  },
  {
    "COUNTY":"WEST POKOT",
    "CONSTITUENCY":"KAPENGURIA",
    "YES":126,
    "NOT":28,
    "TOTAL":154
  },
  {
    "COUNTY":"WEST POKOT",
    "CONSTITUENCY":"POKOT SOUTH",
    "YES":83,
    "NOT":50,
    "TOTAL":133
  },
  {
    "COUNTY":"WEST POKOT",
    "CONSTITUENCY":"SIGOR",
    "YES":125,
    "NOT":8,
    "TOTAL":133
  },
  {
    "COUNTY":"WEST POKOT",
    "CONSTITUENCY":"TOTAL",
    "YES":408,
    "NOT":122,
    "TOTAL":530
  },
  {
    "COUNTY":"",
    "CONSTITUENCY":"GRAND TOTAL",
    "YES":17278,
    "NOT":3880,
    "TOTAL":21158
  }
];